### ISSUE TITLE
Délimitation du bâtiment

### ISSUE THREAD

**Issue by overflorian** [francois2metz/osm-indoor-viewer#1]
Hey,
Que est le tag utilisé pour que le contour d'un bâtiment s'affiche dans ton outil ?
Je pensais, en lisant la doc, que c'était level:ref cf. https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging mais je ne l'ai pas trouvé à montrouge https://www.openstreetmap.org/way/83236349

Le marché de l'olive dans le 18ème https://www.openstreetmap.org/way/84154399 n'affiche en effet pas le contour : https://osm-indoor.2metz.fr/#19.13/48.8909709/2.3615042 alors qu'il apparait bien dans openlevelup https://openlevelup.net/?l=0#20/48.89093/2.36152

autre exemple qui peut aider d'un endroit que j'ai mappé : le petit trianon https://osm-indoor.2metz.fr/#19.49/48.8155657/2.1097658

**Comment by francois2metz** [comment]
Il faut un polygon qui soit taggé en indoor=quelque_chose. C'est ce qui manque à ton marché pour que ça passe bien. Pour le petit trianon, le problème c'est les levels avec plusieurs étages. Faut que je gère ça.

**Comment by francois2metz** [comment]
Dans le wiki ils parlent de mettre `min_level` et `max_level` sur les buildings pour re. Dans les faits ça n'a pas l'air d'être utilisé. 

Merci pour la visite gratuite du Petit Trianon.

**Comment by overflorian** [comment]
Avec plaisir, je vais corriger les données au marché. Et sinon, j'ai le plan du grand trianon, si ça te tente de le mapper... il est mono-niveau. Et puis, j'ai toujours eu ce rêve fou, un jour, de mapper le château principal. Un des plus grands châteaux du Monde ! Des centaines, que dis-je, des milliers de pièces. C'est pas aussi facile que ce que j'ai fait à Chambord. 
Gloire, succès, nuits blanches au programme. Que du bonheur !

**Comment by francois2metz** [comment]
Ce serait top le chateau de Versailles !

**Comment by francois2metz** [comment]
J'ai fait une grosse mise à jour coté données qui règle les multiples étages + d'autres choses qu'il faut que je style.
